version: "3.9"
services:
  global-server:
    container_name: global-server
    build: ../global-server
    ports:
      - 20000:8000
    volumes:
      - ../global-server:/app
      - ./volumn/global-server/DATA_FOLDER:/app/DATA_FOLDER
    environment:
      - MONGODB_URL=mongodb://mongo-global:27017/f3db
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - WHO=global-server
      - USER=admin
      - COLLABORATORS_URL=http://collaborator1:8000,http://collaborator2:8000
      - PYTHONUNBUFFERED=1
  collaborator1:
    container_name: collaborator1
    build: ../collaborator
    ports:
      - 20001:8000
    volumes:
      - ../collaborator:/app
      - ./volumn/collaborator1/DATA_FOLDER:/app/DATA_FOLDER
    environment:
      - MONGODB_URL=mongodb://mongo1:27017/f3db
      - GLOBAL_SERVER_URL=http://global-server:8000
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - WHO=collaborator1
      - USER=admin
      - PYTHONUNBUFFERED=1
      - DATA_FOLDER=./DATA_FOLDER/
      - db_name=f3db
  collaborator2:
    container_name: collaborator2
    build: ../collaborator
    ports:
      - 20002:8000
    volumes:
      - ../collaborator:/app
      - ./volumn/collaborator2/DATA_FOLDER:/app/DATA_FOLDER
    environment:
      - MONGODB_URL=mongodb://mongo2:27017/f3db
      - GLOBAL_SERVER_URL=http://global-server:8000
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - WHO=collaborator2
      - USER=admin
      - PYTHONUNBUFFERED=1
      - DATA_FOLDER=./DATA_FOLDER/
      - db_name=f3db
  mongo-global:
    image: mongo
    volumes:
      - ./volumn/global-server/mongodb:/data/db
    ports:
      - 27027:27017
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=f3db
  mongo1:
    image: mongo
    volumes:
      - ./volumn/collaborator1/mongodb:/data/db
    ports:
      - 27037:27017
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=f3db
  mongo2:
    image: mongo
    volumes:
      - ./volumn/collaborator2/mongodb:/data/db
    ports:
      - 27047:27017
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=f3db
  mongo-seed:
    image: mongo
    volumes:
      - ./seed-data:/seed-data
    command: mongoimport -h mongo1,mongo2 --db f3db -c test --type csv --mode upsert --headerline --file /seed-data/pressures.csv
    depends_on:
      - mongo1
      - mongo2
